GET https://{{host}}:{{port}}
Content-Type: application/json

{
}

###

POST https://{{host}}:{{port}}/wallet/add
Content-Type: application/json

{
  "chain": "{{chain}}",
  "network": "{{network}}",
  "privateKey": "{{walletMnemonic}}",
  "address": null,
  "accountId": null
}

###

GET https://{{host}}:{{port}}/chain/status?chain={{chain}}&network={{network}}
Content-Type: application/json

{
}

###

GET https://{{host}}:{{port}}/chain/config?chain={{chain}}&network={{network}}
Content-Type: application/json

{
}

###

GET https://{{host}}:{{port}}/chain/tokens?chain={{chain}}&network={{network}}
Content-Type: application/json

{
}

###

POST https://{{host}}:{{port}}/chain/balances
Content-Type: application/json

{
  "chain": "{{chain}}",
  "network": "{{network}}",
  "connector": "{{connector}}",
  "address": "{{walletPublicKey}}",
  "tokenSymbols": [
    "USDT",
    "HDX",
    "DOT"
  ]
}

###

POST https://{{host}}:{{port}}/chain/poll
Content-Type: application/json

{
  "chain": "{{chain}}",
  "network": "{{network}}",
  "connector": "{{connector}}",
  "txHash":"{{txHash}}"
}

###

POST https://{{host}}:{{port}}/amm/estimateGas
Content-Type: application/json

{
  "chain": "{{chain}}",
  "network": "{{network}}",
  "connector": "{{connector}}"
}

###

POST https://{{host}}:{{port}}/amm/price
Content-Type: application/json

{
  "chain": "{{chain}}",
  "network": "{{network}}",
  "connector": "{{connector}}",
  "base": "HDX",
  "quote": "USDT",
  "amount": "1",
  "side": "BUY"
}

###

POST https://{{host}}:{{port}}/amm/trade
Content-Type: application/json

{
  "chain":"{{chain}}",
  "network":"{{network}}",
  "connector":"{{connector}}",
  "base": "HDX",
  "quote": "USDT",
  "amount":"1",
  "address":"{{walletPublicKey}}",
  "side": "SELL",
  "limitPrice": null,
  "nonce": null,
  "maxFeePerGas": null,
  "maxPriorityFeePerGas": null,
  "allowedSlippage": null,
  "poolId": null
}

###
